# Generated by Django 5.2 on 2025-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_funds_add',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее пополнение'),
        ),
    ]
